version: '3.4'

services: 
  library.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__LibraryConnectionString=Server=sql;Database=librarydb;User Id=sa;Password=123asdQ!     
      - RedisHost=redis.cache
      - RedisPort=6379
      - RabbitMqConnectionString=host=rabbit
    ports:
      - "8888:80"
    depends_on:   
      - sql
      - redis.cache
      - cache.web

  library.identity.service:
    ports:
      - "8566:80"
      - "44349:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123asdQ
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/identityserver.pfx
      - ASPNETCORE_HTTPS_PORT=44349
    volumes:
      - ~/.aspnet/https:/https:ro
       
  library.presentation.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiUrl=http://library.api/api/    
      - IdentityServiceUrl=https://library.identity.service/
      - ConnectionStrings__AccountsDBConnectionString=Server=sql;Database=accountsdb;User Id=sa;Password=123asdQ!
      - RabbitMqConnectionString=host=rabbit
    ports:
      - "7777:80"
    depends_on:    
      - sql
      - library.api  
      - library.identity.service

  rabbit: 
    ports:
      - "15672:15672"

  sql:
    image: microsoft/mssql-server-linux:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=123asdQ!
    ports:
      - "5433:1433"  

  redis.cache:
    image: redis
    ports:
      - "9999:6379"

  cache.web:    
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOST=redis.cache
    ports:
      - "8081:8081"    