version: '3.4'

services:
  library.api:
    image: ${DOCKER_REGISTRY-}libraryapi
    build:
      context: .
      dockerfile: src/Library.Api/Dockerfile  

  library.presentation.mvc:
    image: ${DOCKER_REGISTRY-}librarypresentationmvc
    build:
      context: .
      dockerfile: src/Library.Presentation.MVC/Dockerfile   

  rabbit: 
    image: rabbitmq:3-management